spring:
  application:
    name: business-owner-service

  datasource:
    url: jdbc:mysql://localhost:3306/business_owner_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-on-validation-error: true
