
spring:
  application:
    name: business-owner-service
  security:
    user:
      name: admin
      password: adminpass


  datasource:
    url: jdbc:mysql://localhost:3306/business_owner_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-on-validation-error: true
server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
